WORLD_X = 30
WORLD_Y = 20
TILESIZE = 32

WIDTH = WORLD_X * TILESIZE
HEIGHT = WORLD_Y * TILESIZE

FPS = 20

n_tree_pct = 0.5
N_TREES = int(WORLD_X * WORLD_Y * n_tree_pct)

N_PATHFINDERS = 8
N_VILLAGES = 10

GRASS_REGROW_RATE = 1000 # ms
GRASS_REGROW_AMT = 20
